package queries

var AddProduct string = "INSERT INTO product VALUES($1,$2,$3,$4,$5,$6)"
var GetProduct string = "SELECT product.product_id,product.name,product.specification,product.sku,category.name,product.price FROM product JOIN category ON product.category_id = category.category_id WHERE product.product_id = $1"
var DeleteProduct string = "DELETE FROM product WHERE product_id = $1"
var GetProductShort string = "SELECT product_id,name,price FROM product"
var UpdateProduct string = "UPDATE product SET "
var AddInventory string = "INSERT INTO inventory VALUES($1,$2)"
var GetInventory string = "SELECT * FROM inventory WHERE product_id = $1"
var DeleteInventory string = "DELETE FROM inventory WHERE product_id = $1"
var UpdateInventory string = "UPDATE inventory SET "
var AddCategory string = "INSERT INTO category VALUES($1,$2)"
var GetCategory string = "SELECT * FROM category WHERE category_id = $1"
var DeleteCategory string = "DELETE FROM category WHERE category_id = $1"
var UpdateCategory string = "UPDATE category SET "
var CreateCartReference string = "INSERT INTO cart_reference VALUES($1,$2)"
var GetReference string = "SELECT * FROM cart_reference WHERE ref=$1"
var GetQuantityInventory string = "SELECT quantity FROM inventory WHERE product_id=$1"
var GetCartItem string = "SELECT * FROM cart_item WHERE ref=$1 AND product_id=$2"
var UpdateCartQuantity string = "UPDATE cart_item SET quantity=$1 WHERE ref=$2 AND product_id=$3"
var CartInsert string = "INSERT INTO cart_item VALUES($1,$2,$3)"
var UpdateInventoryQuantity string = "UPDATE inventory SET quantity=$1 WHERE product_id=$2"
var GetCart string = "SELECT cart_item.ref,cart_item.product_id,product.name,product.specification,category.name,product.price,cart_item.quantity FROM (cart_item JOIN product ON cart_item.product_id = product.product_id) JOIN category ON category.category_id = product.product_id WHERE cart_item.ref=$1"
var DeleteCart string = "DELETE FROM cart_item WHERE ref = $1 AND product_id = $2"
var UpdateCart string = "UPDATE cart_item SET "
